#!/usr/local/bin/node

let fs = require("fs");
let Phrase = require("./index.js");

let text = fs.readFileSync("phrases.txt", "utf-8");
filteredText = text.split("\n").filter(line => {
  let phrase = new Phrase(line);
  return (phrase.palindrome());
}).join("\n");
fs.writeFileSync("palindromes.txt", filteredText)
console.log("Saved!");
